---
camera:
  sensor_mode: HDR # options: [HDR, high_res, medium_res, low_res]
  quality : HIGH #VERY_HIGH, HIGH, MEDIUM, LOW, VERY_LOW

display:
  enable: True
  size_x: 800
  size_y: 480
  horizontal_flip: False
  vertical_flip: False
  title_fields: ["ExposureTime", "FrameDuration", "Lux"]

 